services:

  gin_example_db:
    image: postgres
    restart: always
    networks:
      - gin_example
    ports:
      - 5432:5432
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: password
      POSTGRES_DB: gin_example

networks:
  gin_example:
    name: "gin_example"
